### ISSUE TITLE
about path and file_rec/async source

### ISSUE THREAD

**Issue by keitee** [Shougo/neomru.vim#21]
Hello,

I have couple of questions about unite and unite mru.

1. When use file_mru and file_rec both, file_rec shows relative path but mur shows absolute path. Is there any way to make them use the same way?

2. When use both, is there any way to remove duplicates and shows only unique entries?

Many thanks

**Comment by Shougo** [comment]
> When use file_mru and file_rec both, file_rec shows relative path but mur shows absolute path. Is there any way to make them use the same way?

```vim
call unite#custom#source('file_mru', 'converters', 'converter_relative_word')

> When use both, is there any way to remove duplicates and shows only unique entries?

```vim
Unite file_mru file_rec/async -unique
```

**Comment by keitee** [comment]
That works for me. Many thanks.
