### ISSUE TITLE
Import from v:oldfiles

### ISSUE THREAD

**Issue by bohrshaw** [Shougo/neomru.vim#22]
Someone interested in this could give it a spin. I just imported them manually.
`:h v:oldfiles`

**Comment by Shougo** [comment]
I can implement it.
But why this feature is useful?

Please explain it.

**Comment by bohrshaw** [comment]
It's useful the first time using this plugin. As otherwise, the initial list of MRU files is empty or only contains a little few after a short usage. So, by populating the list from the *meaningful* history of `v:oldfiles`, the user is ready to go.

**Comment by bstaint** [comment]
It's will be duplicate entries.
Windows:
![1](https://cloud.githubusercontent.com/assets/5853792/8148405/d3df47f6-12ce-11e5-9261-2340fcf9e6ec.png)

**Comment by Shougo** [comment]
Fixed.  But @bstaint clear the mru file.

**Comment by bstaint** [comment]
@Shougo I know, Thanks.

**Comment by Shougo** [comment]
???

It is fixed or not fixed?
Your explanation is hard to understand.

**Comment by bstaint** [comment]
two issues:
one is `substitute_path_separator`,It has been fixed.
another when open vim neomru duplicate entries. I think need call s:uniq after load oldfiles.

**Comment by Shougo** [comment]
I will improve the feature.
The import is `NeoMRUImportFile` only.

**Comment by Shougo** [comment]
Implemented.
