### ISSUE TITLE
How to not ignore files from /mnt?

### ISSUE THREAD

**Issue by PonderingGrower** [Shougo/neomru.vim#25]
Hi,

I just found out that NeoMRU ignores files in `/mnt/`(https://github.com/Shougo/neomru.vim/blob/master/autoload/neomru.vim#L69).

How can I stop that behaviour?

I tried this:
````
let g:unite_source_file_mru_ignore_pattern = substitute(g:neomru#file_mru_ignore_pattern, '|\/mnt\/\\', '', '')
````
But it didn't work.

Also I'm not sure if this is the right approach as the [docs](https://github.com/Shougo/neomru.vim/blob/master/doc/neomru.txt#L120) say `This variable is deprecated. Please use unite#custom#source() instead.` but that sounds to me like a way of filtering what results show up, not what files get saved in `$XDG_CACHE_HOME/neomru/file`.

**Comment by Shougo** [comment]
```vim
let g:neomru#file_mru_ignore_pattern =
      \'\~$\|\.\%(o\|exe\|dll\|bak\|zwc\|pyc\|sw[po]\)$'.
      \'\|\%(^\|/\)\.\%(hg\|git\|bzr\|svn\)\%($\|/\)'.
      \'\|^\%(\\\\\|/media/\|/temp/\|/tmp/\|\%(/private\)\=/var/folders/\)'.
      \'\|\%(^\%(fugitive\)://\)'
```

**Comment by rodhash** [comment]
> ```viml
> let g:neomru#file_mru_ignore_pattern =
>       \'\~$\|\.\%(o\|exe\|dll\|bak\|zwc\|pyc\|sw[po]\)$'.
>       \'\|\%(^\|/\)\.\%(hg\|git\|bzr\|svn\)\%($\|/\)'.
>       \'\|^\%(\\\\\|/media/\|/temp/\|/tmp/\|\%(/private\)\=/var/folders/\)'.
>       \'\|\%(^\%(fugitive\)://\)'
> ```

Thank you
