### ISSUE TITLE
error on open

### ISSUE THREAD

**Issue by jamesdunham** [Shougo/neomru.vim#30]
Hi, I'm getting this error in NVIM 0.1.2 on OSX 10.11.
```
Error detected while processing function <SNR>51_append..neomru#_append..67..64:
line    9:
E688: More targets than List items
```

I can produce it by opening or switching buffers (`:e foo`). A minimal .vimrc:
```
set nocompatible
set runtimepath+=~/.vim/bundle/neomru.vim
```

Without neomru in the .vimrc, the errors don't appear. I've tried deleting and reinstalling neomru without success, on the disk or through NeoBundle. 

This started after a system disk filled up and NVIM was unable to write files to disk.

Thanks!

**Comment by Shougo** [comment]
Fixed.

**Comment by jamesdunham** [comment]
Yes!
