### ISSUE TITLE
quick-match didn't show quick match keys

### ISSUE THREAD

**Issue by jchain** [Shougo/neomru.vim#31]
Hi Shougo,

Do you have the similar issue?
If I run `Unite -quick-match file_mru<cr>` the mru window shows but no quick match keys show. `quick-match buffer` works OK. I use the latest `Unite` and `neomru`

Thanks,

**Comment by Shougo** [comment]
I cannot reproduce the problem.
Please create minimal .vimrc less than 50 lines.
I will check it.

**Comment by jchain** [comment]
OK. The culprit is this line

    let g:unite_split_rule = 'botright'

Can you reproduce the problem by adding the line above?

**Comment by Shougo** [comment]
Fixed.  Please update unite.vim
