### ISSUE TITLE
MRU list ruined when using multiple instances of Vim

### ISSUE THREAD

**Issue by lervag** [Shougo/neomru.vim#32]
Create test directory and two empty files:

```sh
cd ~
mkdir mru-test
cd mru-test
touch test1
touch test2
```

Now consider the following minimal vimrc file:

```vim
set nocompatible
let &rtp = '~/.vim/bundle/unite.vim,' . &rtp
let &rtp = '~/.vim/bundle/neomru.vim,' . &rtp
filetype plugin indent on
syntax enable

let g:neomru#file_mru_path = '~/mru-test/file'
let g:neomru#directory_mru_path = '~/mru-test/directory'
```

Now:

1. Open `vim -u vimrc test1` in one terminal.
2. Open `vim -u vimrc test2` in a second terminal. Then quit.
3. Then quit the `test1` Vim session.
4. Finally, `cat file`

```
-> cat file
0.3.0
/home/lervag/mru-test/test1
```

For some reason, the `test2` file is forgotten. That is, I would expect this to be:

```
-> cat file
0.3.0
/home/lervag/mru-test/test1
/home/lervag/mru-test/test2
```

**Comment by Shougo** [comment]
Fixed.

**Comment by lervag** [comment]
Thanks!
