### ISSUE TITLE
store in ~/.local/share/nvim/neomru instead of ~/.cache/neomru

### ISSUE THREAD

**Issue by nhooyr** [Shougo/neomru.vim#37]
I know I can change it myself but I think it would be more appropriate to have `~/.local/share/nvim/neomru` as the default directory because the MRU list is quite essential. I would be quite annoyed if it was gone, it is frustrating to build it again.

Also, Neovim stores the Shada file in `$XDG_DATA_HOME/nvim/shada/main.shada`. While the purpose of the MRU list is different from the Shada file, I think they are close enough to make the comparison. Data about what the user is doing should be stored in `$XDG_DATA_HOME`.

**Comment by Shougo** [comment]
I don't want to change the directory.
It is easy to change the default, but it breaks current users MRU file.
