### ISSUE TITLE
extremely slow

### ISSUE THREAD

**Issue by tex** [Shougo/neomru.vim#39]
Hi Shougo,

this function is causing extreme slowness, when opening mru, but also when switching between other buffers.

Is it possible to make some switch that could turn off this functionality?

function! s:is_file_exist(path) abort  "{{{
  let ignore = !empty(g:neomru#file_mru_ignore_pattern)
        \ && a:path =~ g:neomru#file_mru_ignore_pattern
  return !ignore && (getftype(a:path) ==# 'file' || a:path =~ '^\h\w\+:')
endfunction"}}}

**Comment by Shougo** [comment]
The extremely slowness?
Really?
Please upload the profile result.
`:help profile`

**Comment by Shougo** [comment]
You can configure by `g:neomru#do_validate` variable.

**Comment by tex** [comment]
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
   28  61.305483   0.013711  unite#candidates#_recache()
   28  61.239399   0.012811  <SNR>109_recache_candidates_loop()
    2  60.111677   0.000131  unite#helper#call_source_filters()
    2  60.068836   0.000015  57()
    2  60.068821  60.014548  <SNR>105_converter()
    1  58.945844   0.000217  unite#helper#call_unite()
    1  58.926475   0.013740  unite#start()
    1  58.910257   0.015981  unite#start#standard()
   64  19.043951   0.001181  <SNR>31_append()
   60  19.042770   0.220857  neomru#_append()
  110  18.782641   0.025572  45()
   23  18.706890   0.019927  42()
24060  17.993580             <SNR>106_is_file_exist()
   23  17.785358   0.121508  47()
    5   6.941353   0.002235  unite#action#do()
   15   4.488253   0.023223  65()
   13   3.698792   0.022799  <SNR>132_execute_command()
   13   3.674487   0.133083  unite#util#smart_execute_command()
    1   2.795083   0.000156  94()
   11   2.789261   0.000211  unite#take_action()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
    2  60.068821  60.014548  <SNR>105_converter()
24060             17.993580  <SNR>106_is_file_exist()
  228   1.825235   1.824514  <SNR>68_FindAncestor()
   24              0.831545  <SNR>106_uniq_by()
  217   0.711909   0.410442  <SNR>125_get_action_table()
   18   0.635341   0.400772  <SNR>14_LoadFTPlugin()
 1072              0.320550  noscrollbar#statusline()
   18   0.451839   0.304762  <SNR>17_SynSet()
  244              0.272852  <SNR>101_get_filetime()
  256   0.325630   0.224066  unite#init#_default_scripts()
   60  19.042770   0.220857  neomru#_append()
  244   0.466918   0.194066  unite#sources#file#create_vimfiler_dict()
   18   0.185890   0.185281  <SNR>15_LoadIndent()
  481              0.139851  <SNR>83_Highlight_Matching_Pair()
    4   0.144006   0.139601  _oblique_on_change()
   13   3.674487   0.133083  unite#util#smart_execute_command()
   23  17.785358   0.121508  47()
   44              0.109441  vimfiler#variables#get_data_directory()
   98              0.101034  signature#mark#GetList()
 2545              0.094686  signature#sign#Remove()


FUNCTION  <SNR>106_is_file_exist()
Called 24060 times
Total time:  17.993580
 Self time:  17.993580

count  total (s)   self (s)
24060              0.894175   let ignore = !empty(g:neomru#file_mru_ignore_pattern) && a:path =~ g:neomru#file_mru_ignore_pattern
24060             17.081861   return !ignore && (getftype(a:path) ==# 'file' || a:path =~ '^\h\w\+:')

**Comment by tex** [comment]
Lots of files, Windows OS...

**Comment by Shougo** [comment]
OK.  It is too slow.  But you can disable it by `g:neomru#do_validate`.

**Comment by tex** [comment]
Thanks!
