### ISSUE TITLE
Any API to add files to the mru list?

### ISSUE THREAD

**Issue by mMontu** [Shougo/neomru.vim#44]
I'm using `denite#custom#action()` to add special handling in some cases, and even though the file isn't open on Vim I'd like to add it to the mru list.

Is there any way to do it? Or is it necessary to expose [`s:mru.append(path)`](https://github.com/Shougo/neomru.vim/blob/master/autoload/neomru.vim#L213)

**Comment by Shougo** [comment]
`neomru#_append()` exists.
But it does not take any arguments.
You can add the feature.  The PR is wellcome.

https://github.com/Shougo/neomru.vim/blob/master/autoload/neomru.vim#L311
