### ISSUE TITLE
Version check with different variable type

### ISSUE THREAD

**Issue by ichitera** [Shougo/neomru.vim#47]
In `s:mru.version_check`, String type and Float type are compared, which causes the following error:
```
Error detected while processing function <SNR>41_append[6]..neomru#_append[4]..neomru#append[29]..23[1]..21[20]..24:
line    1:
E892: Using a String as a Float
E892: Using a String as a Float
```
This is the location of the comparison mentioned above.
https://github.com/Shougo/neomru.vim/blob/0126deb4d38b497e3c81e5226b275392c1dbce3a/autoload/neomru.vim#L236-L237

This is the original definition of `self.version`.
https://github.com/Shougo/neomru.vim/blob/0126deb4d38b497e3c81e5226b275392c1dbce3a/autoload/neomru.vim#L28

**Steps to reproduce the issue:**
1. Open vim
2. Execute `:e something.txt`
3. (The error will occur)

**Environment:**
- OS: Windows 10 64bit
- Vim: 8.1.960

**Comment by Shougo** [comment]
Fixed
