### ISSUE TITLE
g:neomru#filename_format documentation is unclear

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [Shougo/neomru.vim#50]
Following the documentation, I've tried this:

```viml
let g:neomru#filename_format = ':.'
```

… with no luck.

How do I removing the leading portion of the path shown in Denite, so that it matches my `file/rec` results?

<img width="897" alt="Screen Shot 2020-01-29 at 20 09 51" src="https://user-images.githubusercontent.com/200/73414067-53390580-42d3-11ea-8461-79013c7fceb0.png">

**Comment by Shougo** [comment]
You can improve the documentation.
It is open source project.

> How do I removing the leading portion of the path shown in Denite, so that it matches my file/rec results?

Your configuration already works.
`LICENSE`, `4061.json`, `DCO.md` already removed leading portion.

Do you want to remove `~/Sync/Code/...` candidates?
If so, you should use `matcher/project_files`.

My example:

```vim
call denite#custom#source('file/old', 'matchers',
      \ ['matcher/fruzzy', 'matcher/project_files'])
```
